baseURL: http://example.org/
languageCode: en-us
title: Portfolio website for Mateo Albin
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Mateo and I was born and raised in Guatemala. I then moved to The Netherlands for my bachelor studies in Economics and I am now living in London and studying at LBS. Welcome to my personal website.
  blog: {}
  contact:
    address: 
      - city: London
        country: United Kingdom
        street: Gloucester Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mateoa.mfa2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
   #   - icon: fa-twitter
  #      label:  Twitter
   #     url: https://www.twitter.com
  #    - icon: fa-facebook
  #      label: Facebook
  #      url: https://www.facebook.com
  #    - icon: fa-instagram
  #      label: Instagram
  #      url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/mateoalbin
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/mateoalbin/
  image: ''
  name: Mateo Albin
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
    #  - name: Generic Blog
    #    url: blogs/ipsum
     # - name: Elements #
     #   url: elements.html #
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Risk-return tradeoff is an investment principle that indicates that the higher the risk, the higher the potential reward.
        title: Risk Return
        url: blogs/risk_return
      - image: pic02.jpg
        subtitle: I studied at Erasmus University Rotterdam
        title: Undergraduate University
        url: https://www.eur.nl/en
      - image: pic03.jpg
        subtitle: My favourite football team is Club Nacional de Football
        title: Club Nacional de Football
        url: https://nacional.uy/es
      - image: pic04.jpg
        subtitle: I currently study the MFA at London Business School.
        title: MFA LBS
        url: https://www.london.edu/masters-degrees/masters-in-financial-analysis
      - image: pic05.jpg
        subtitle: My family is from Uruguay.
        title: Uruguay
        url: https://es.wikipedia.org/wiki/Uruguay
      - image: pic06.jpg
        subtitle: I was born in Guatemala
        title: Guatemala
        url: https://es.wikipedia.org/wiki/Guatemala
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
markup: 
  goldmark: 
    renderer: 
      unsafe: true